theme: jekyll-theme-minimal
title: Marcus Tan's Personal Portfolio
description: A portfolio website built using Jekyll, Gulp, Github-Pages.
url: https://marcustan.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marcus Tan
user_description: Description here
user_title: Full-Stack Developer-TO-BE
email: marcus@mtss.dev
stackoverflow_username: marcustan-dev
github_username:  marcustan-dev
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
